version: '3.8'

services:
  user-service:
    build: ./food-delivery-app/user-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_NAME=food_delivery
      - DB_USER=postgres
      - DB_PASS=Sagnik@09
      - DB_HOST=postgres
      - DB_PORT=5432

  restaurant-service:
    build: ./food-delivery-app/restaurant-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DB_NAME=food_delivery
      - DB_USER=postgres
      - DB_PASS=Sagnik@09
      - DB_HOST=postgres
      - DB_PORT=5432

  delivery-agent-service:
    build: ./food-delivery-app/delivery-agent-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      - DB_NAME=food_delivery
      - DB_USER=postgres
      - DB_PASS=Sagnik@09
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
